/// Flutter icons SentinelxIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SentinelxIcons
///      fonts:
///       - asset: fonts/SentinelxIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SentinelxIcons {
  SentinelxIcons._();

  static const _kFontFam = 'SentinelxIcons';

  static const IconData segwit = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData xpub = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData scan_qr = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData qr_scan = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData onion_tor = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bitcoin = const IconData(0xf15a, fontFamily: _kFontFam);
}
