/// Flutter icons SentinelIconSet
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SentinelIconSet
///      fonts:
///       - asset: fonts/SentinelIconSet.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class SentinelIconSet {
  SentinelIconSet._();

  static const _kFontFam = 'SentinelIconSet';
  static const _kFontPkg = null;

  static const IconData signal = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_paste = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restore_page = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_arrow = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
